version: '2'

networks:
  mired2:
    ipam:
      config:
        - subnet: 182.28.0.0/16
          gateway: 182.28.0.1

services:
  db:
    image: bitnami/mongodb:latest
    container_name: mongo_DB
    networks:
      mired2:
        ipv4_address: 182.28.0.11
    ports:
      - "27017:27017"
    expose:
      - 27017

  agenda:
    image: gbarlop330/contactos:contactos2
    container_name: agendaApp
    networks:
      mired2:
        ipv4_address: 182.28.0.12
    expose:
      - 80
    ports:
      - "80:8090"
    depends_on:
      - db

  tutorial:
    image: gbarlop330/sha256:1
    container_name: TutorialApp
    networks:
      mired2:
        ipv4_address: 182.28.0.13
    expose:
      - 81
    ports:
      - "81:8098"
    depends_on:
      - db